services:
  hugo:
    build:
      context: .
      target: dev
    container_name: modern-xp-guide
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - loco

networks:
  loco:
    external: true
