baseURL = "https://modernxp.jorpo.co/"
languageCode = "en"
title = "Modern XP: A Field Guide"
theme = "epaper"
disableKinds = ["rss", "taxonomy", "term"]
enableGitInfo = false
summaryLength = 0
buildFuture = true

[params]
  description = "A field guide for Modern XP — agile practices for shipping small, learning fast, and containing complexity."
  author = "Jorpo.co"
  umami_id = "e2568b03-c064-4b7f-87b7-e0ec625ce81e"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
