api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/tls.yml
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"